# hadoop docker-compose
hdfs:
  build: ./Doc/docker/hdfs
  ports:
    - "8020:8020"
    - "8022:8022"
  volumes:
    - .:/app
hive:
  build: ./Doc/docker/hive
  ports:
    - "10000:10000"
  volumes:
    - .:/app
sftp:
    image: atmoz/sftp
    volumes:
        - .:/home/vinkOS/archivosVisitas
    ports:
        - "2222:22"
    networks:
      static-network:
        ipv4_address: 172.17.0.10
    command: usuario:vink0s:1001
